### ISSUE TITLE
Check mouse state

### ISSUE THREAD

**Issue by rleddy** [PuruVJ/svelte-drag#22]
So, I put this into vedges (an SVGEdit -- svelte version)

It's a nice idea. But, I ran into problems in two different contexts. 

1) I can drag rulers. Cool! But, you can always expect the mouse to get ahead of the element being dragged. So, if you do mouseUp when your dragging element goes past the boundary (which it does at time) the element will still be dragging. So, you need to check that the mouse is actually in the desired state for dragging.

2) I tried this for drag handles on an edit region and gave up. The thing went crazy. Not too long all the handles were all over the place being dragged while the mouse was up.  So, I had to put my own handle dragging code into can_edit (a submodule -- may make into an npm component at some point.

I am not sure of what to expect from your code passed in options. So, I am not putting time into figuring it out at the moment.

But, the main issue is that the mouse state needs to be checked. There should be some double checking on bounds as well. 

Otherwise, I like the idea of this component (action). It would be good to make it robust.

**Comment by PuruVJ** [comment]
As for the first one, the thing you can do is apply bounds in the options config, limit it to the left or right of the viewport or the container. `bounds` options will help there

Can you share a reproduction for the 2nd? a Svelte REPL would be good to see what's going wrong

**Comment by rleddy** [comment]
The first thing, the parent has been used as the bounds element. 

I have implemented drag more than a few times. And, I am usually having to do some trick with the bounds. It's easy to get the mouse ahead of the element. So, events will miss the target. 

The second thing is related. But, it takes a complex of items all with a drag action (svelte drag). These are sibling components. And, the are all set to have absolute position.

**Comment by rleddy** [comment]
So, after using it more, it seems that scrolling is related to the issue. 

So, the parent element forms the bounds well. But, the parent element scrolls partly out of sight (intentionally). The drag target stays in place (also intentionally).

So, you can then drag the target element into the hidden area. And, then you can't get the drag target back. 

So, I will look at your docs again. But, I was not sure how to use the parent as the scroll bound and to limit scrolling to the first initial visible area (not scrolled yet). Of course, there is programming a whole new thing. But, really, it would be nice to avoid that.
