### ISSUE TITLE
Grid Snap Not Working?

### ISSUE THREAD

**Issue by jrmoynihan** [PuruVJ/svelte-drag#31]
Hey, love the clean API on this package!

Just having some trouble getting grid-snapping to work.  Can you provide an example, or elucidate what might be wrong with the following code?  I'm not seeing any snap behavior change with or without the grid options provided in the DragOptions object.
![image](https://user-images.githubusercontent.com/65916939/150537036-9c2cf0a8-d867-444d-a5c2-915cabd576bf.png)

**Comment by PuruVJ** [comment]
Can you make svelte REPL of this example please?

**Comment by jrmoynihan** [comment]
I figured it out!  I interpreted the grid array to be the number of grid _divisions_ (i.e. a 2x2 grid), not the pixel dimensions of each grid block (i.e. an infinite grid with snap points every 2px vertically and 2px horizontally).  I would clarify that in the docs for other naive users.

**Comment by PuruVJ** [comment]
Thanks, ill update the docs

**Comment by jrmoynihan** [comment]
I did encounter a second, somewhat related issue though:  When using a defined grid, I can't move an item back to its original position.  If I move an item from its [0, 0] position, I can't move it back to that origin.
[REPL](https://svelte.dev/repl/5339703d32e6456aa2ee23d393472bc9?version=3.46.2)

Am I not setting something correctly?

**Comment by PuruVJ** [comment]
Yur right, it's definitely a bug. I'll look into it.

**Comment by jrmoynihan** [comment]
Thanks for checking it out.  I also noticed that when dragging two items on top of each other, they can end up having _very_ slightly different translation distances (different by ~1px or less than a pixel).  I think this is a subpixel calculation/rendering difference across browsers.

When creating the grid, does the action create _exact_ grid tile locations that the element can travel to, or is the position re-calculated, say, upon translation?  I'm just wondering if that behavior can be made more predictable to avoid this issue.

I was trying to detect if two elements were overlapping after a drag event (so I could move one of them out of the way), but wasn't getting consistent results when I dragged items on top of each other.  This might be easier if the `onDragEnd` event returned the expected location of the element (i.e. the grid [x,y] coordinates, not the translation offset).  I could then store the coordinates from `onDragEnd` and check if they match another draggable item's stored coordinates, rather than checking the pixels from `getBoundClientRect()` or parsing out the `element.style.transform`.

What do you think?

**Comment by PuruVJ** [comment]
Seems good to me. I think I can expose a domRect property in all the events

**Comment by PuruVJ** [comment]
Should be fixed now.

About the domRect, I will make a release soon with the fix and this feature included

**Comment by PuruVJ** [comment]
Released in [2.5.0](https://github.com/PuruVJ/svelte-drag/releases/tag/2.5.0)
