### ISSUE TITLE
Minor fix - readme.md handle example 

### ISSUE THREAD

**Issue by jesslawnz** [PuruVJ/svelte-drag#4]
handle example in the readme.md has the wrong options object. looks like copy/paste snafu.

thanks for the awesome work!

`<div use:draggable={{ cancel: '.cancel' }}>
  You shall not drag!!🧙‍♂️
  <div class="handle">This will drag 😁</div>
</div>`

Should be:

`<div use:draggable={{ handle: '.handle' }}>
  You shall not drag!!🧙‍♂️
  <div class="handle">This will drag 😁</div>
</div>`

**Comment by PuruVJ** [comment]
Oh crap!! 🥵🥵

Thanks for reminding. I just went through whole readme, and it's full of such stuff, I'll fix it right away!

Thanks for the heads up!

**Comment by PuruVJ** [comment]
Fixed!
