### ISSUE TITLE
Allow controlled behavior

### ISSUE THREAD

**Issue by PuruVJ** [PuruVJ/svelte-drag#6]
`react-draggable` library allows you to dynamically change the current `x` and `y`, getting rid of user controls, only controllable by the user.

Implement this

Would love your comments on this if you got any

**Comment by PuruVJ** [comment]
@ngaer Check this example and see whether it looks good or not, for controlled API https://svelte.dev/repl/ba7aecd8a1fa47a1aca59607bb1d0d41?version=3.44.1

Gist: Element will drag when you drag with mouse, but it can also be moved by setting the `controlledPosition` option. In that way, it doesn't trigger any events, doesn't follow any grid. Completely controlled by the values it is passed. 

Can still be moved programmatically when `disabled`.

I tried to be as close to `react-draggable` API, but willing to diverge from it a bit

**Comment by ngaer** [comment]
@PuruVJ overall it works good, but I found one issue: 

If I set `controlledPosition` to `{ x: 0, y: 0 }`, it doesn't work, while any other values (e.g. `{ x: 10, y: 0 }`) seem to work well. Here's the gist with an example - https://svelte.dev/repl/016856b4b0c14e40be823a5cf12634ac?version=3.44.1

**Comment by PuruVJ** [comment]
Ah crap, shoulda used `??` instead of `||` 🥲🥲

**Comment by PuruVJ** [comment]
Change svelte-drag version to 2.1.0-beta.1 and try again, it is working now

**Comment by ngaer** [comment]
Yeah, I think `??` should work well here.

**Comment by ngaer** [comment]
Great, it works.

**Comment by PuruVJ** [comment]
Fixed in #20

**Comment by PuruVJ** [comment]
@ngaer @eranmiller check out latest release, and the new docs. there's a `Controlled vs Uncontrolled` section in the README now with lot of examples
